# Generated by Django 4.2.11 on 2024-04-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lesson_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='cover',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='module',
            name='cover',
            field=models.URLField(blank=True),
        ),
    ]
